-- customers table
CREATE TABLE customers
(
    id      SERIAL PRIMARY KEY,
    name    VARCHAR(100) NOT NULL,
    user_id INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE app_languages
(
    code CHAR(2) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO app_languages (code, name)
VALUES ('ca', 'Catalan'),
       ('en', 'English'),
       ('es', 'Spanish'),
       ('it', 'Italian');

CREATE TABLE app_labels
(
    code     VARCHAR(50)  NOT NULL,
    language CHAR(2),
    text     VARCHAR(500) NOT NULL,
    PRIMARY KEY (code, language),
    FOREIGN KEY (language) REFERENCES app_languages (code) ON DELETE CASCADE
);

-- english labels
INSERT INTO app_labels (language, code, text)
VALUES ('en', 'ADD_BOOK', 'Add book'),
       ('en', 'ADD_BOOK_MANUALLY', 'Add book manually'),
       ('en', 'STOCK_CODE', 'Stock code'),
       ('en', 'CODE', 'Code'),
       ('en', 'CLOSE', 'Close'),
       ('en', 'DELETE', 'Delete'),
       ('en', 'CANCEL', 'Cancel'),
       ('en', 'SAVE', 'Save'),
       ('en', 'ADD', 'Add'),
       ('en', 'UPDATE', 'Update'),
       ('en', 'ACTIONS', 'Actions'),
       ('en', 'ADD_AND_PRINT', 'Add & print'),
       ('en', 'SEARCH_BOOKS', 'Search books'),
       ('en', 'DASHBOARD', 'Dashboard'),
       ('en', 'LIBRARY', 'Library'),
       ('en', 'IMAGE', 'Image'),
       ('en', 'LOCATIONS', 'Locations'),
       ('en', 'LOCATION', 'Location'),
       ('en', 'NO_LOCATION', '[No location]'),
       ('en', 'CATEGORIES', 'Categories'),
       ('en', 'CATEGORY', 'Category'),
       ('en', 'CUSTOMERS', 'Customers'),
       ('en', 'AUTHORS', 'Authors'),
       ('en', 'SETTINGS', 'Settings'),
       ('en', 'LOG_OUT', 'Log out'),
       ('en', 'SCAN_BARCODE', 'Scan barcode'),
       ('en', 'ERROR_OCCURRED', 'An error has occurred'),
       ('en', 'SNACKBAR_NEW_AUTHOR_ADDED', 'New author added:'),
       ('en', 'SNACKBAR_AUTHOR_DELETED', 'Author has been deleted successfully'),
       ('en', 'BOOK', 'Book'),
       ('en', 'SNACKBAR_NEW_CATEGORY_ADDED', 'Category was been added successfully'),
       ('en', 'SNACKBAR_DELETED_CATEGORY', 'Category was been deleted successfully'),
       ('en', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'Customer has been added successfully'),
       ('en', 'SNACKBAR_DELETED_CUSTOMER', 'Customer has been deleted successfully'),
       ('en', 'SNACKBAR_NEW_LOCATION_ADDED', 'Location has been added successfully'),
       ('en', 'SNACKBAR_LOCATION_UPDATED', 'Location has been updated successfully'),
       ('en', 'SNACKBAR_DELETED_LOCATION', 'Location has been deleted successfully'),
       ('en', 'SNACKBAR_AUTHOR_UPDATED', 'Author updated successfully'),
       ('en', 'SNACKBAR_BOOK_STOCK_ADDED', 'Book stock has been added'),
       ('en', 'SNACKBAR_BOOK_STOCK_DELETED', 'Book stock deleted successfully'),
       ('en', 'SNACKBAR_BOOK_STOCK_UPDATED', 'Book stock updated successfully'),
       ('en', 'SNACKBAR_BOOK_UPDATED', 'Book updated successfully'),
       ('en', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'Book image has been changed'),
       ('en', 'SNACKBAR_BOOK_DELETED', 'Book has been deleted'),
       ('en', 'BOOKED', 'Booked'),
       ('en', 'AVAILABLE', 'Available'),
       ('en', 'NOT_AVAILABLE', 'Not available'),
       ('en', 'DAMAGE', 'Damage'),
       ('en', 'SNACKBAR_CATEGORY_UPDATED', 'Category was updated successfully'),
       ('en', 'SNACKBAR_PROFILE_UPDATED', 'Profile information updated successfully'),
       ('en', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'Profile image has been removed successfully'),
       ('en', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'Profile image has been updated successfully'),
       ('en', 'EDIT_AUTHOR', 'Edit author'),
       ('en', 'ADD_AUTHOR', 'Add author'),
       ('en', 'NAME', 'Name'),
       ('en', 'DELETE_AUTHOR_TITLE', 'Delete author '),
       ('en', 'DELETE_AUTHOR_DESC', 'Are you sure that you want to remove this author?'),
       ('en', 'IMAGE_DRAG_AND_DROP', 'Drag and drop an image'),
       ('en', 'BOOK_HOVER_INFO', '(Hover to change book image)'),
       ('en', 'EDIT_BOOK_STOCK', 'Edit book stock'),
       ('en', 'ADD_BOOK_STOCK', 'Add book stock'),
       ('en', 'BOOK_STOCK_INFO',        'Book stock represents individual copies of a book, allowing you to track quantity and status. Each book stock has a unique barcode for identification. Please ensure the stock barcode is added to the book.'),
       ('en', 'BOOK_STOCK_STATUS', 'Status'),
       ('en', 'BOOKED_BY', 'Booked by'),
       ('en', 'DELETE_STOCK', 'Delete stock'),
       ('en', 'DELETE_STOCK_DESC', 'Are you sure that you want to remove this book stock?'),
       ('en', 'LANGUAGE', 'Language'),
       ('en', 'FORMAT', 'Format'),
       ('en', 'PAGES', 'Pages'),
       ('en', 'PUBLISHER', 'Publisher'),
       ('en', 'PUBLISHED_DATE', 'Published date'),
       ('en', 'DESCRIPTION', 'Description'),
       ('en', 'DELETE_BOOK', 'Delete book '),
       ('en', 'DELETE_BOOK_DESC', 'Are you sure that you want to delete this book?'),
       ('en', 'DELETE_CATEGORY', 'Delete category '),
       ('en', 'DELETE_CATEGORY_DESC', 'Are you sure that you want to remove this category ?'),
       ('en', 'ADD_A_BOOK', 'Add a Book'),
       ('en', 'REMOVE_BOOK', 'Remove book'),
       ('en', 'REMOVE_BOOK_DESC', 'Are you sure that you want to remove this book from this customer ?'),
       ('en', 'EDIT_CUSTOMER', 'Edit customer'),
       ('en', 'ADD_CUSTOMER', 'Add customer'),
       ('en', 'TOTAL_BOOKS', 'Total books'),
       ('en', 'DELETE_CUSTOMER', 'Delete customer '),
       ('en', 'DELETE_CUSTOMER_DESC', 'Are you sure that you want to remove this customer?'),
       ('en', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Books Added Over Time'),
       ('en', 'DASHBOARD_TOTAL', 'Total'),
       ('en', 'RELEASE', 'Release'),
       ('en', 'DASHBOARD_CHART', 'Chart'),
       ('en', 'DASHBOARD_LAST_BOOKS', 'Last books'),
       ('en', 'EDIT_LOCATION', 'Edit location'),
       ('en', 'ADD_LOCATION', 'Add location'),
       ('en', 'DELETE_LOCATION', 'Delete location '),
       ('en', 'DELETE_LOCATION_DESC', 'Are you sure that you want to remove this location ?'),
       ('en', 'NOT_FOUND_DESC', 'The page was not found.'),
       ('en', 'NOT_FOUND_GO_HOME', 'Go to home'),
       ('en', 'ADD_BOOK_ISBN', 'Add book (ISBN)'),
       ('en', 'ADD_BOOK_ISBN_DESC',        'Easily add a book to your library by entering its ISBN code. The app will automatically fetch the book''s details, including title, author, description, and more, and seamlessly add it to your collection.'),
       ('en', 'ISBN_CODE', 'ISBN code'),
       ('en', 'INVALID_ISBN_CODE', 'Invalid ISBN format. Please enter a valid ISBN-10 or ISBN-13.'),
       ('en', 'DRAG_AND_DROP_BOOK_COVER', 'Drag and drop book cover'),
       ('en', 'USERCONF_CHANGE_PASSWORD', 'Change password'),
       ('en', 'USERCONF_CURRENT_PASSWORD', 'Current password'),
       ('en', 'USERCONF_NEW_PASSWORD', 'New password'),
       ('en', 'USERCONF_PASSWORD_SECURITY', 'Please add all necessary characters to create safe password.'),
       ('en', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'At least 8 characters'),
       ('en', 'USERCONF_PASSWORD_UPPERCASE', 'At least one uppercase letter'),
       ('en', 'USERCONF_PASSWORD_ONE_NUMBER', 'At least one number'),
       ('en', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'At least one special character'),
       ('en', 'USEERCONF_PASSWORD_REPEAT', 'Repeat new password'),
       ('en', 'USERCONF_PASSWORD_NOT_MATCH', 'Passwords do not match!'),
       ('en', 'USERCONF_PASSWORD_CHANGED', 'Password changed successfully'),
       ('en', 'USERCONF_CHANGE_IMAGE', 'Change image'),
       ('en', 'USERCONF_REMOVE_IMAGE', 'Remove image'),
       ('en', 'USERCONF_IMAGE_SUPPORT', 'We only support PNGs, JPGs under 2MB'),
       ('en', 'USERCONF_NAME', 'Name'),
       ('en', 'USERCONF_LANGUAGE_REGION', 'Language & Region'),
       ('en', 'USERCONF_LANGUAGE', 'Language'),
       ('en', 'USERCONF_REGION', 'Region'),
       ('en', 'USERCONF_ACCOUNT_SECURITY', 'Account Security'),
       ('en', 'USERCONF_EMAIL', 'Email'),
       ('en', 'USERCONF_CHANGE_PASSWORD_DESC',      'Update your account password to keep your account secure. You’ll need to enter your current password and choose a new one that meets security requirements.'),
       ('en', 'USERCONF_DELETE_DESC', 'Permanently delete the account and remove workspace and books.'),
       ('en', 'USERCONF_DELETE', 'Delete account'),
       ('en', 'USERCONF_DELETE_USER_TITLE', 'Delete user'),
       ('en', 'USERCONF_DELETE_USER_DESC',       'Are you sure you want to delete your Paper Books account? This will permanently remove your account and all associated content."'),
       ('en', 'USERCONF_IMAGE_FORMAT_ALERT', 'Please upload a PNG or JPEG image.'),
       ('en', 'USERCONF_IMAGE_SIZE_ALERT', 'File size must be less than 2MB');

-- spanish labels
INSERT INTO app_labels (language, code, text)
VALUES ('es', 'ADD_BOOK', 'Agregar libro'),
       ('es', 'ADD_BOOK_MANUALLY', 'Agregar libro manualmente'),
       ('es', 'STOCK_CODE', 'Código de stock'),
       ('es', 'CODE', 'Código'),
       ('es', 'CLOSE', 'Cerrar'),
       ('es', 'DELETE', 'Eliminar'),
       ('es', 'CANCEL', 'Cancelar'),
       ('es', 'SAVE', 'Guardar'),
       ('es', 'ADD', 'Agregar'),
       ('es', 'UPDATE', 'Actualizar'),
       ('es', 'ACTIONS', 'Acciones'),
       ('es', 'ADD_AND_PRINT', 'Agregar e imprimir'),
       ('es', 'SEARCH_BOOKS', 'Buscar libros'),
       ('es', 'DASHBOARD', 'Panel'),
       ('es', 'LIBRARY', 'Biblioteca'),
       ('es', 'IMAGE', 'Imagen'),
       ('es', 'LOCATIONS', 'Ubicaciones'),
       ('es', 'LOCATION', 'Ubicación'),
       ('es', 'NO_LOCATION', '[Sin ubicación]'),
       ('es', 'CATEGORIES', 'Categorías'),
       ('es', 'CATEGORY', 'Categoría'),
       ('es', 'CUSTOMERS', 'Clientes'),
       ('es', 'AUTHORS', 'Autores'),
       ('es', 'SETTINGS', 'Configuración'),
       ('es', 'LOG_OUT', 'Cerrar sesión'),
       ('es', 'SCAN_BARCODE', 'Escanear código de barras'),
       ('es', 'ERROR_OCCURRED', 'Ha ocurrido un error'),
       ('es', 'SNACKBAR_NEW_AUTHOR_ADDED', 'Nuevo autor agregado:'),
       ('es', 'SNACKBAR_AUTHOR_DELETED', 'El autor se ha eliminado correctamente'),
       ('es', 'BOOK', 'Libro'),
       ('es', 'SNACKBAR_NEW_CATEGORY_ADDED', 'La categoría se ha agregado correctamente'),
       ('es', 'SNACKBAR_DELETED_CATEGORY', 'La categoría se ha eliminado correctamente'),
       ('es', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'El cliente se ha agregado correctamente'),
       ('es', 'SNACKBAR_DELETED_CUSTOMER', 'El cliente se ha eliminado correctamente'),
       ('es', 'SNACKBAR_NEW_LOCATION_ADDED', 'La ubicación se ha agregado correctamente'),
       ('es', 'SNACKBAR_LOCATION_UPDATED', 'La ubicación se ha actualizado correctamente'),
       ('es', 'SNACKBAR_DELETED_LOCATION', 'La ubicación se ha eliminado correctamente'),
       ('es', 'SNACKBAR_AUTHOR_UPDATED', 'El autor se ha actualizado correctamente'),
       ('es', 'SNACKBAR_BOOK_STOCK_ADDED', 'Se ha agregado el stock del libro'),
       ('es', 'SNACKBAR_BOOK_STOCK_DELETED', 'El stock del libro se ha eliminado correctamente'),
       ('es', 'SNACKBAR_BOOK_STOCK_UPDATED', 'El stock del libro se ha actualizado correctamente'),
       ('es', 'SNACKBAR_BOOK_UPDATED', 'El libro se ha actualizado correctamente'),
       ('es', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'La imagen del libro se ha cambiado'),
       ('es', 'SNACKBAR_BOOK_DELETED', 'El libro se ha eliminado'),
       ('es', 'BOOKED', 'Reservado'),
       ('es', 'AVAILABLE', 'Disponible'),
       ('es', 'NOT_AVAILABLE', 'No disponible'),
       ('es', 'DAMAGE', 'Dañado'),
       ('es', 'SNACKBAR_CATEGORY_UPDATED', 'La categoría se ha actualizado correctamente'),
       ('es', 'SNACKBAR_PROFILE_UPDATED', 'La información del perfil se ha actualizado correctamente'),
       ('es', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'La imagen del perfil se ha eliminado correctamente'),
       ('es', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'La imagen del perfil se ha actualizado correctamente'),
       ('es', 'EDIT_AUTHOR', 'Editar autor'),
       ('es', 'ADD_AUTHOR', 'Agregar autor'),
       ('es', 'NAME', 'Nombre'),
       ('es', 'DELETE_AUTHOR_TITLE', 'Eliminar autor'),
       ('es', 'DELETE_AUTHOR_DESC', '¿Seguro que deseas eliminar este autor?'),
       ('es', 'IMAGE_DRAG_AND_DROP', 'Arrastra y suelta una imagen'),
       ('es', 'BOOK_HOVER_INFO', '(Pasa el cursor para cambiar la imagen del libro)'),
       ('es', 'EDIT_BOOK_STOCK', 'Editar stock de libro'),
       ('es', 'ADD_BOOK_STOCK', 'Agregar stock de libro'),
       ('es', 'BOOK_STOCK_INFO',       'El stock de libros representa copias individuales de un libro, lo que permite realizar un seguimiento de la cantidad y el estado. Cada copia tiene un código de barras único para su identificación. Asegúrate de agregar el código de barras del stock al libro.'),
       ('es', 'BOOK_STOCK_STATUS', 'Estado'),
       ('es', 'BOOKED_BY', 'Reservado por'),
       ('es', 'DELETE_STOCK', 'Eliminar stock'),
       ('es', 'DELETE_STOCK_DESC', '¿Seguro que deseas eliminar este stock de libro?'),
       ('es', 'LANGUAGE', 'Idioma'),
       ('es', 'FORMAT', 'Formato'),
       ('es', 'PAGES', 'Páginas'),
       ('es', 'PUBLISHER', 'Editorial'),
       ('es', 'PUBLISHED_DATE', 'Fecha de publicación'),
       ('es', 'DESCRIPTION', 'Descripción'),
       ('es', 'DELETE_BOOK', 'Eliminar libro'),
       ('es', 'DELETE_BOOK_DESC', '¿Seguro que deseas eliminar este libro?'),
       ('es', 'DELETE_CATEGORY', 'Eliminar categoría'),
       ('es', 'DELETE_CATEGORY_DESC', '¿Seguro que deseas eliminar esta categoría?'),
       ('es', 'ADD_A_BOOK', 'Agregar un libro'),
       ('es', 'REMOVE_BOOK', 'Eliminar libro'),
       ('es', 'REMOVE_BOOK_DESC', '¿Seguro que deseas eliminar este libro de este cliente?'),
       ('es', 'EDIT_CUSTOMER', 'Editar cliente'),
       ('es', 'ADD_CUSTOMER', 'Agregar cliente'),
       ('es', 'TOTAL_BOOKS', 'Total de libros'),
       ('es', 'DELETE_CUSTOMER', 'Eliminar cliente'),
       ('es', 'DELETE_CUSTOMER_DESC', '¿Seguro que deseas eliminar este cliente?'),
       ('es', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Libros agregados a lo largo del tiempo'),
       ('es', 'DASHBOARD_TOTAL', 'Total'),
       ('es', 'RELEASE', 'Lanzamiento'),
       ('es', 'DASHBOARD_CHART', 'Gráfico'),
       ('es', 'DASHBOARD_LAST_BOOKS', 'Últimos libros'),
       ('es', 'EDIT_LOCATION', 'Editar ubicación'),
       ('es', 'ADD_LOCATION', 'Agregar ubicación'),
       ('es', 'DELETE_LOCATION', 'Eliminar ubicación'),
       ('es', 'DELETE_LOCATION_DESC', '¿Seguro que deseas eliminar esta ubicación?'),
       ('es', 'NOT_FOUND_DESC', 'Página no encontrada.'),
       ('es', 'NOT_FOUND_GO_HOME', 'Ir al inicio'),
       ('es', 'ADD_BOOK_ISBN', 'Agregar libro (ISBN)'),
       ('es', 'ADD_BOOK_ISBN_DESC',        'Agrega fácilmente un libro a tu biblioteca introduciendo su código ISBN. La aplicación obtendrá automáticamente los detalles del libro, incluyendo título, autor, descripción y más, y lo agregará a tu colección.'),
       ('es', 'ISBN_CODE', 'Código ISBN'),
       ('es', 'INVALID_ISBN_CODE', 'Formato de ISBN inválido. Introduce un ISBN-10 o ISBN-13 válido.'),
       ('es', 'DRAG_AND_DROP_BOOK_COVER', 'Arrastra y suelta la portada del libro'),
       ('es', 'USERCONF_CHANGE_PASSWORD', 'Cambiar contraseña'),
       ('es', 'USERCONF_CURRENT_PASSWORD', 'Contraseña actual'),
       ('es', 'USERCONF_NEW_PASSWORD', 'Nueva contraseña'),
       ('es', 'USERCONF_PASSWORD_SECURITY', 'Agrega todos los caracteres necesarios para crear una contraseña segura.'),
       ('es', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'Al menos 8 caracteres'),
       ('es', 'USERCONF_PASSWORD_UPPERCASE', 'Al menos una letra mayúscula'),
       ('es', 'USERCONF_PASSWORD_ONE_NUMBER', 'Al menos un número'),
       ('es', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'Al menos un carácter especial'),
       ('es', 'USEERCONF_PASSWORD_REPEAT', 'Repite la nueva contraseña'),
       ('es', 'USERCONF_PASSWORD_NOT_MATCH', '¡Las contraseñas no coinciden!'),
       ('es', 'USERCONF_PASSWORD_CHANGED', 'Contraseña cambiada correctamente'),
       ('es', 'USERCONF_CHANGE_IMAGE', 'Cambiar imagen'),
       ('es', 'USERCONF_REMOVE_IMAGE', 'Eliminar imagen'),
       ('es', 'USERCONF_IMAGE_SUPPORT', 'Solo aceptamos PNG o JPG de menos de 2 MB'),
       ('es', 'USERCONF_NAME', 'Nombre'),
       ('es', 'USERCONF_LANGUAGE_REGION', 'Idioma y región'),
       ('es', 'USERCONF_LANGUAGE', 'Idioma'),
       ('es', 'USERCONF_REGION', 'Región'),
       ('es', 'USERCONF_ACCOUNT_SECURITY', 'Seguridad de la cuenta'),
       ('es', 'USERCONF_EMAIL', 'Correo electrónico'),
       ('es', 'USERCONF_CHANGE_PASSWORD_DESC',        'Actualiza la contraseña de tu cuenta para mantenerla segura. Deberás introducir tu contraseña actual y elegir una nueva que cumpla los requisitos de seguridad.'),
       ('es', 'USERCONF_DELETE_DESC', 'Elimina permanentemente la cuenta y borra el espacio de trabajo y los libros.'),
       ('es', 'USERCONF_DELETE', 'Eliminar cuenta'),
       ('es', 'USERCONF_DELETE_USER_TITLE', 'Eliminar usuario'),
       ('es', 'USERCONF_DELETE_USER_DESC',        '¿Seguro que deseas eliminar tu cuenta de Paper Books? Esto eliminará permanentemente tu cuenta y todo el contenido asociado.'),
       ('es', 'USERCONF_IMAGE_FORMAT_ALERT', 'Por favor, sube una imagen en formato PNG o JPEG.'),
       ('es', 'USERCONF_IMAGE_SIZE_ALERT', 'El tamaño del archivo debe ser inferior a 2 MB');

-- catalan labels
INSERT INTO app_labels (language, code, text)
VALUES ('ca', 'ADD_BOOK', 'Afegeix llibre'),
       ('ca', 'ADD_BOOK_MANUALLY', 'Afegeix llibre manualment'),
       ('ca', 'STOCK_CODE', 'Codi d’estoc'),
       ('ca', 'CODE', 'Codi'),
       ('ca', 'CLOSE', 'Tanca'),
       ('ca', 'DELETE', 'Elimina'),
       ('ca', 'CANCEL', 'Cancel·la'),
       ('ca', 'SAVE', 'Desa'),
       ('ca', 'ADD', 'Afegeix'),
       ('ca', 'UPDATE', 'Actualitza'),
       ('ca', 'ACTIONS', 'Accions'),
       ('ca', 'ADD_AND_PRINT', 'Afegeix i imprimeix'),
       ('ca', 'SEARCH_BOOKS', 'Cerca llibres'),
       ('ca', 'DASHBOARD', 'Panell'),
       ('ca', 'LIBRARY', 'Biblioteca'),
       ('ca', 'IMAGE', 'Imatge'),
       ('ca', 'LOCATIONS', 'Ubicacions'),
       ('ca', 'LOCATION', 'Ubicació'),
       ('ca', 'NO_LOCATION', '[Sense ubicació]'),
       ('ca', 'CATEGORIES', 'Categories'),
       ('ca', 'CATEGORY', 'Categoria'),
       ('ca', 'CUSTOMERS', 'Clients'),
       ('ca', 'AUTHORS', 'Autors'),
       ('ca', 'SETTINGS', 'Configuració'),
       ('ca', 'LOG_OUT', 'Tanca la sessió'),
       ('ca', 'SCAN_BARCODE', 'Escaneja codi de barres'),
       ('ca', 'ERROR_OCCURRED', 'S’ha produït un error'),
       ('ca', 'SNACKBAR_NEW_AUTHOR_ADDED', 'Nou autor afegit:'),
       ('ca', 'SNACKBAR_AUTHOR_DELETED', 'L’autor s’ha eliminat correctament'),
       ('ca', 'BOOK', 'Llibre'),
       ('ca', 'SNACKBAR_NEW_CATEGORY_ADDED', 'La categoria s’ha afegit correctament'),
       ('ca', 'SNACKBAR_DELETED_CATEGORY', 'La categoria s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'El client s’ha afegit correctament'),
       ('ca', 'SNACKBAR_DELETED_CUSTOMER', 'El client s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_NEW_LOCATION_ADDED', 'La ubicació s’ha afegit correctament'),
       ('ca', 'SNACKBAR_LOCATION_UPDATED', 'La ubicació s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_DELETED_LOCATION', 'La ubicació s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_AUTHOR_UPDATED', 'L’autor s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_BOOK_STOCK_ADDED', 'S’ha afegit l’estoc del llibre'),
       ('ca', 'SNACKBAR_BOOK_STOCK_DELETED', 'S’ha eliminat l’estoc del llibre correctament'),
       ('ca', 'SNACKBAR_BOOK_STOCK_UPDATED', 'S’ha actualitzat l’estoc del llibre correctament'),
       ('ca', 'SNACKBAR_BOOK_UPDATED', 'El llibre s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'La imatge del llibre s’ha canviat'),
       ('ca', 'SNACKBAR_BOOK_DELETED', 'El llibre s’ha eliminat'),
       ('ca', 'BOOKED', 'Reservat'),
       ('ca', 'AVAILABLE', 'Disponible'),
       ('ca', 'NOT_AVAILABLE', 'No disponible'),
       ('ca', 'DAMAGE', 'Danyat'),
       ('ca', 'SNACKBAR_CATEGORY_UPDATED', 'La categoria s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_PROFILE_UPDATED', 'La informació del perfil s’ha actualitzat correctament'),
       ('ca', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'La imatge del perfil s’ha eliminat correctament'),
       ('ca', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'La imatge del perfil s’ha actualitzat correctament'),
       ('ca', 'EDIT_AUTHOR', 'Edita autor'),
       ('ca', 'ADD_AUTHOR', 'Afegeix autor'),
       ('ca', 'NAME', 'Nom'),
       ('ca', 'DELETE_AUTHOR_TITLE', 'Elimina autor'),
       ('ca', 'DELETE_AUTHOR_DESC', 'Estàs segur que vols eliminar aquest autor?'),
       ('ca', 'IMAGE_DRAG_AND_DROP', 'Arrossega i deixa anar una imatge'),
       ('ca', 'BOOK_HOVER_INFO', '(Passa el cursor per canviar la imatge del llibre)'),
       ('ca', 'EDIT_BOOK_STOCK', 'Edita estoc de llibre'),
       ('ca', 'ADD_BOOK_STOCK', 'Afegeix estoc de llibre'),
       ('ca', 'BOOK_STOCK_INFO',        'L’estoc de llibres representa còpies individuals d’un llibre, permetent fer el seguiment de la quantitat i l’estat. Cada exemplar té un codi de barres únic per a la seva identificació. Assegura’t d’afegir el codi de barres de l’estoc al llibre.'),
       ('ca', 'BOOK_STOCK_STATUS', 'Estat'),
       ('ca', 'BOOKED_BY', 'Reservat per'),
       ('ca', 'DELETE_STOCK', 'Elimina estoc'),
       ('ca', 'DELETE_STOCK_DESC', 'Estàs segur que vols eliminar aquest estoc de llibre?'),
       ('ca', 'LANGUAGE', 'Idioma'),
       ('ca', 'FORMAT', 'Format'),
       ('ca', 'PAGES', 'Pàgines'),
       ('ca', 'PUBLISHER', 'Editorial'),
       ('ca', 'PUBLISHED_DATE', 'Data de publicació'),
       ('ca', 'DESCRIPTION', 'Descripció'),
       ('ca', 'DELETE_BOOK', 'Elimina llibre'),
       ('ca', 'DELETE_BOOK_DESC', 'Estàs segur que vols eliminar aquest llibre?'),
       ('ca', 'DELETE_CATEGORY', 'Elimina categoria'),
       ('ca', 'DELETE_CATEGORY_DESC', 'Estàs segur que vols eliminar aquesta categoria?'),
       ('ca', 'ADD_A_BOOK', 'Afegeix un llibre'),
       ('ca', 'REMOVE_BOOK', 'Elimina llibre'),
       ('ca', 'REMOVE_BOOK_DESC', 'Estàs segur que vols eliminar aquest llibre d’aquest client?'),
       ('ca', 'EDIT_CUSTOMER', 'Edita client'),
       ('ca', 'ADD_CUSTOMER', 'Afegeix client'),
       ('ca', 'TOTAL_BOOKS', 'Total de llibres'),
       ('ca', 'DELETE_CUSTOMER', 'Elimina client'),
       ('ca', 'DELETE_CUSTOMER_DESC', 'Estàs segur que vols eliminar aquest client?'),
       ('ca', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Llibres afegits al llarg del temps'),
       ('ca', 'DASHBOARD_TOTAL', 'Total'),
       ('ca', 'RELEASE', 'Llançament'),
       ('ca', 'DASHBOARD_CHART', 'Gràfic'),
       ('ca', 'DASHBOARD_LAST_BOOKS', 'Últims llibres'),
       ('ca', 'EDIT_LOCATION', 'Edita ubicació'),
       ('ca', 'ADD_LOCATION', 'Afegeix ubicació'),
       ('ca', 'DELETE_LOCATION', 'Elimina ubicació'),
       ('ca', 'DELETE_LOCATION_DESC', 'Estàs segur que vols eliminar aquesta ubicació?'),
       ('ca', 'NOT_FOUND_DESC', 'No s’ha trobat la pàgina.'),
       ('ca', 'NOT_FOUND_GO_HOME', 'Vés a l’inici'),
       ('ca', 'ADD_BOOK_ISBN', 'Afegeix llibre (ISBN)'),
       ('ca', 'ADD_BOOK_ISBN_DESC',        'Afegeix fàcilment un llibre a la teva biblioteca introduint el seu codi ISBN. L’aplicació obtindrà automàticament les dades del llibre, incloent títol, autor, descripció i més, i l’afegirà a la teva col·lecció.'),
       ('ca', 'ISBN_CODE', 'Codi ISBN'),
       ('ca', 'INVALID_ISBN_CODE', 'Format d’ISBN invàlid. Introdueix un ISBN-10 o ISBN-13 vàlid.'),
       ('ca', 'DRAG_AND_DROP_BOOK_COVER', 'Arrossega i deixa anar la coberta del llibre'),
       ('ca', 'USERCONF_CHANGE_PASSWORD', 'Canvia la contrasenya'),
       ('ca', 'USERCONF_CURRENT_PASSWORD', 'Contrasenya actual'),
       ('ca', 'USERCONF_NEW_PASSWORD', 'Contrasenya nova'),
       ('ca', 'USERCONF_PASSWORD_SECURITY', 'Afegeix tots els caràcters necessaris per crear una contrasenya segura.'),
       ('ca', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'Com a mínim 8 caràcters'),
       ('ca', 'USERCONF_PASSWORD_UPPERCASE', 'Com a mínim una lletra majúscula'),
       ('ca', 'USERCONF_PASSWORD_ONE_NUMBER', 'Com a mínim un número'),
       ('ca', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'Com a mínim un caràcter especial'),
       ('ca', 'USEERCONF_PASSWORD_REPEAT', 'Repeteix la nova contrasenya'),
       ('ca', 'USERCONF_PASSWORD_NOT_MATCH', 'Les contrasenyes no coincideixen!'),
       ('ca', 'USERCONF_PASSWORD_CHANGED', 'Contrasenya canviada correctament'),
       ('ca', 'USERCONF_CHANGE_IMAGE', 'Canvia la imatge'),
       ('ca', 'USERCONF_REMOVE_IMAGE', 'Elimina la imatge'),
       ('ca', 'USERCONF_IMAGE_SUPPORT', 'Només acceptem PNG o JPG de menys de 2 MB'),
       ('ca', 'USERCONF_NAME', 'Nom'),
       ('ca', 'USERCONF_LANGUAGE_REGION', 'Idioma i regió'),
       ('ca', 'USERCONF_LANGUAGE', 'Idioma'),
       ('ca', 'USERCONF_REGION', 'Regió'),
       ('ca', 'USERCONF_ACCOUNT_SECURITY', 'Seguretat del compte'),
       ('ca', 'USERCONF_EMAIL', 'Correu electrònic'),
       ('ca', 'USERCONF_CHANGE_PASSWORD_DESC',        'Actualitza la contrasenya del compte per mantenir-lo segur. Caldrà introduir la contrasenya actual i triar-ne una de nova que compleixi els requisits de seguretat.'),
       ('ca', 'USERCONF_DELETE_DESC', 'Suprimeix permanentment el compte i elimina l’espai de treball i els llibres.'),
       ('ca', 'USERCONF_DELETE', 'Elimina compte'),
       ('ca', 'USERCONF_DELETE_USER_TITLE', 'Elimina usuari'),
       ('ca', 'USERCONF_DELETE_USER_DESC',        'Estàs segur que vols eliminar el teu compte de Paper Books? Això eliminarà permanentment el teu compte i tot el contingut associat.'),
       ('ca', 'USERCONF_IMAGE_FORMAT_ALERT', 'Si us plau, puja una imatge en format PNG o JPEG.'),
       ('ca', 'USERCONF_IMAGE_SIZE_ALERT', 'La mida del fitxer ha de ser inferior a 2 MB');

-- italian labels
INSERT INTO app_labels (language, code, text)
VALUES ('it', 'ADD_BOOK', 'Aggiungi libro'),
       ('it', 'ADD_BOOK_MANUALLY', 'Aggiungi libro manualmente'),
       ('it', 'STOCK_CODE', 'Codice stock'),
       ('it', 'CODE', 'Codice'),
       ('it', 'CLOSE', 'Chiudi'),
       ('it', 'DELETE', 'Elimina'),
       ('it', 'CANCEL', 'Annulla'),
       ('it', 'SAVE', 'Salva'),
       ('it', 'ADD', 'Aggiungi'),
       ('it', 'UPDATE', 'Aggiorna'),
       ('it', 'ACTIONS', 'Azioni'),
       ('it', 'ADD_AND_PRINT', 'Aggiungi e stampa'),
       ('it', 'SEARCH_BOOKS', 'Cerca libri'),
       ('it', 'DASHBOARD', 'Dashboard'),
       ('it', 'LIBRARY', 'Biblioteca'),
       ('it', 'IMAGE', 'Immagine'),
       ('it', 'LOCATIONS', 'Posizioni'),
       ('it', 'LOCATION', 'Posizione'),
       ('it', 'NO_LOCATION', '[Nessuna posizione]'),
       ('it', 'CATEGORIES', 'Categorie'),
       ('it', 'CATEGORY', 'Categoria'),
       ('it', 'CUSTOMERS', 'Clienti'),
       ('it', 'AUTHORS', 'Autori'),
       ('it', 'SETTINGS', 'Impostazioni'),
       ('it', 'LOG_OUT', 'Esci'),
       ('it', 'SCAN_BARCODE', 'Scansiona codice a barre'),
       ('it', 'ERROR_OCCURRED', 'Si è verificato un errore'),
       ('it', 'SNACKBAR_NEW_AUTHOR_ADDED', 'Nuovo autore aggiunto:'),
       ('it', 'SNACKBAR_AUTHOR_DELETED', 'L’autore è stato eliminato con successo'),
       ('it', 'BOOK', 'Libro'),
       ('it', 'SNACKBAR_NEW_CATEGORY_ADDED', 'La categoria è stata aggiunta con successo'),
       ('it', 'SNACKBAR_DELETED_CATEGORY', 'La categoria è stata eliminata con successo'),
       ('it', 'SNACKBAR_NEW_CUSTOMER_ADDED', 'Il cliente è stato aggiunto con successo'),
       ('it', 'SNACKBAR_DELETED_CUSTOMER', 'Il cliente è stato eliminato con successo'),
       ('it', 'SNACKBAR_NEW_LOCATION_ADDED', 'La posizione è stata aggiunta con successo'),
       ('it', 'SNACKBAR_LOCATION_UPDATED', 'La posizione è stata aggiornata con successo'),
       ('it', 'SNACKBAR_DELETED_LOCATION', 'La posizione è stata eliminata con successo'),
       ('it', 'SNACKBAR_AUTHOR_UPDATED', 'Autore aggiornato con successo'),
       ('it', 'SNACKBAR_BOOK_STOCK_ADDED', 'Stock del libro aggiunto'),
       ('it', 'SNACKBAR_BOOK_STOCK_DELETED', 'Stock del libro eliminato con successo'),
       ('it', 'SNACKBAR_BOOK_STOCK_UPDATED', 'Stock del libro aggiornato con successo'),
       ('it', 'SNACKBAR_BOOK_UPDATED', 'Libro aggiornato con successo'),
       ('it', 'SNACKBAR_BOOK_IMAGE_UPDATED', 'L’immagine del libro è stata modificata'),
       ('it', 'SNACKBAR_BOOK_DELETED', 'Il libro è stato eliminato'),
       ('it', 'BOOKED', 'Prenotato'),
       ('it', 'AVAILABLE', 'Disponibile'),
       ('it', 'NOT_AVAILABLE', 'Non disponibile'),
       ('it', 'DAMAGE', 'Danneggiato'),
       ('it', 'SNACKBAR_CATEGORY_UPDATED', 'Categoria aggiornata con successo'),
       ('it', 'SNACKBAR_PROFILE_UPDATED', 'Informazioni profilo aggiornate con successo'),
       ('it', 'SNACKBAR_PROFILE_IMAGE_DELETED', 'Immagine del profilo rimossa con successo'),
       ('it', 'SNACKBAR_PROFILE_IMAGE_UPDATED', 'Immagine del profilo aggiornata con successo'),
       ('it', 'EDIT_AUTHOR', 'Modifica autore'),
       ('it', 'ADD_AUTHOR', 'Aggiungi autore'),
       ('it', 'NAME', 'Nome'),
       ('it', 'DELETE_AUTHOR_TITLE', 'Elimina autore'),
       ('it', 'DELETE_AUTHOR_DESC', 'Sei sicuro di voler rimuovere questo autore?'),
       ('it', 'IMAGE_DRAG_AND_DROP', 'Trascina e rilascia un’immagine'),
       ('it', 'BOOK_HOVER_INFO', '(Passa il cursore per cambiare l’immagine del libro)'),
       ('it', 'EDIT_BOOK_STOCK', 'Modifica stock libro'),
       ('it', 'ADD_BOOK_STOCK', 'Aggiungi stock libro'),
       ('it', 'BOOK_STOCK_INFO',       'Lo stock del libro rappresenta copie individuali di un libro, permettendo di monitorarne quantità e stato. Ogni copia ha un codice a barre univoco per l’identificazione. Assicurati di aggiungere il codice a barre dello stock al libro.'),
       ('it', 'BOOK_STOCK_STATUS', 'Stato'),
       ('it', 'BOOKED_BY', 'Prenotato da'),
       ('it', 'DELETE_STOCK', 'Elimina stock'),
       ('it', 'DELETE_STOCK_DESC', 'Sei sicuro di voler eliminare questo stock di libro?'),
       ('it', 'LANGUAGE', 'Lingua'),
       ('it', 'FORMAT', 'Formato'),
       ('it', 'PAGES', 'Pagine'),
       ('it', 'PUBLISHER', 'Editore'),
       ('it', 'PUBLISHED_DATE', 'Data di pubblicazione'),
       ('it', 'DESCRIPTION', 'Descrizione'),
       ('it', 'DELETE_BOOK', 'Elimina libro'),
       ('it', 'DELETE_BOOK_DESC', 'Sei sicuro di voler eliminare questo libro?'),
       ('it', 'DELETE_CATEGORY', 'Elimina categoria'),
       ('it', 'DELETE_CATEGORY_DESC', 'Sei sicuro di voler rimuovere questa categoria?'),
       ('it', 'ADD_A_BOOK', 'Aggiungi un libro'),
       ('it', 'REMOVE_BOOK', 'Rimuovi libro'),
       ('it', 'REMOVE_BOOK_DESC', 'Sei sicuro di voler rimuovere questo libro da questo cliente?'),
       ('it', 'EDIT_CUSTOMER', 'Modifica cliente'),
       ('it', 'ADD_CUSTOMER', 'Aggiungi cliente'),
       ('it', 'TOTAL_BOOKS', 'Totale libri'),
       ('it', 'DELETE_CUSTOMER', 'Elimina cliente'),
       ('it', 'DELETE_CUSTOMER_DESC', 'Sei sicuro di voler eliminare questo cliente?'),
       ('it', 'DASHBOARD_BOOKS_ADDED_TIME_OVER_TIME', 'Libri aggiunti nel tempo'),
       ('it', 'DASHBOARD_TOTAL', 'Totale'),
       ('it', 'RELEASE', 'Rilascio'),
       ('it', 'DASHBOARD_CHART', 'Grafico'),
       ('it', 'DASHBOARD_LAST_BOOKS', 'Ultimi libri'),
       ('it', 'EDIT_LOCATION', 'Modifica posizione'),
       ('it', 'ADD_LOCATION', 'Aggiungi posizione'),
       ('it', 'DELETE_LOCATION', 'Elimina posizione'),
       ('it', 'DELETE_LOCATION_DESC', 'Sei sicuro di voler rimuovere questa posizione?'),
       ('it', 'NOT_FOUND_DESC', 'Pagina non trovata.'),
       ('it', 'NOT_FOUND_GO_HOME', 'Vai alla home'),
       ('it', 'ADD_BOOK_ISBN', 'Aggiungi libro (ISBN)'),
       ('it', 'ADD_BOOK_ISBN_DESC',        'Aggiungi facilmente un libro alla tua biblioteca inserendo il suo codice ISBN. L’app recupererà automaticamente i dettagli del libro, inclusi titolo, autore, descrizione e altro, aggiungendolo alla tua collezione.'),
       ('it', 'ISBN_CODE', 'Codice ISBN'),
       ('it', 'INVALID_ISBN_CODE', 'Formato ISBN non valido. Inserisci un ISBN-10 o ISBN-13 valido.'),
       ('it', 'DRAG_AND_DROP_BOOK_COVER', 'Trascina e rilascia la copertina del libro'),
       ('it', 'USERCONF_CHANGE_PASSWORD', 'Cambia password'),
       ('it', 'USERCONF_CURRENT_PASSWORD', 'Password attuale'),
       ('it', 'USERCONF_NEW_PASSWORD', 'Nuova password'),
       ('it', 'USERCONF_PASSWORD_SECURITY', 'Aggiungi tutti i caratteri necessari per creare una password sicura.'),
       ('it', 'USERCONF_PASSWORD_MINIMUM_CHAR', 'Almeno 8 caratteri'),
       ('it', 'USERCONF_PASSWORD_UPPERCASE', 'Almeno una lettera maiuscola'),
       ('it', 'USERCONF_PASSWORD_ONE_NUMBER', 'Almeno un numero'),
       ('it', 'USERCONF_PASSWORD_SPECIAL_CHAR', 'Almeno un carattere speciale'),
       ('it', 'USEERCONF_PASSWORD_REPEAT', 'Ripeti la nuova password'),
       ('it', 'USERCONF_PASSWORD_NOT_MATCH', 'Le password non coincidono!'),
       ('it', 'USERCONF_PASSWORD_CHANGED', 'Password cambiata con successo'),
       ('it', 'USERCONF_CHANGE_IMAGE', 'Cambia immagine'),
       ('it', 'USERCONF_REMOVE_IMAGE', 'Rimuovi immagine'),
       ('it', 'USERCONF_IMAGE_SUPPORT', 'Supportiamo solo PNG o JPG inferiori a 2 MB'),
       ('it', 'USERCONF_NAME', 'Nome'),
       ('it', 'USERCONF_LANGUAGE_REGION', 'Lingua e regione'),
       ('it', 'USERCONF_LANGUAGE', 'Lingua'),
       ('it', 'USERCONF_REGION', 'Regione'),
       ('it', 'USERCONF_ACCOUNT_SECURITY', 'Sicurezza dell’account'),
       ('it', 'USERCONF_EMAIL', 'Email'),
       ('it', 'USERCONF_CHANGE_PASSWORD_DESC',        'Aggiorna la password del tuo account per mantenerlo sicuro. Dovrai inserire la password attuale e sceglierne una nuova che soddisfi i requisiti di sicurezza.'),
       ('it', 'USERCONF_DELETE_DESC', 'Elimina definitivamente l’account e rimuove spazio di lavoro e libri.'),
       ('it', 'USERCONF_DELETE', 'Elimina account'),
       ('it', 'USERCONF_DELETE_USER_TITLE', 'Elimina utente'),
       ('it', 'USERCONF_DELETE_USER_DESC',        'Sei sicuro di voler eliminare il tuo account Paper Books? Questo rimuoverà definitivamente il tuo account e tutto il contenuto associato.'),
       ('it', 'USERCONF_IMAGE_FORMAT_ALERT', 'Carica un’immagine in formato PNG o JPEG.'),
       ('it', 'USERCONF_IMAGE_SIZE_ALERT', 'La dimensione del file deve essere inferiore a 2 MB');

-- Users table
CREATE TABLE users
(
    id              SERIAL PRIMARY KEY,
    code            VARCHAR(50) UNIQUE  NOT NULL,
    name            VARCHAR(100)        NOT NULL,
    password        VARCHAR(64)         NOT NULL,
    email           VARCHAR(100) UNIQUE NOT NULL,
    last_login_date TIMESTAMP,
    created_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    image           BYTEA,
    language        CHAR(2)   DEFAULT 'en',
    region          CHAR(2)   DEFAULT 'US',
    FOREIGN KEY (language) REFERENCES app_languages (code) ON DELETE SET NULL
);

-- Locations table
CREATE TABLE locations
(
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    user_id     INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Categories table
CREATE TABLE categories
(
    id      SERIAL PRIMARY KEY,
    name    VARCHAR(100) NOT NULL UNIQUE,
    user_id INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Languages table
CREATE TABLE languages
(
    code CHAR(2) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO languages (code, name)
VALUES ('ar', 'Arabic'),
       ('bn', 'Bengali'),
       ('ca', 'Catalan'),
       ('de', 'German'),
       ('en', 'English'),
       ('es', 'Spanish'),
       ('fr', 'French'),
       ('hi', 'Hindi'),
       ('id', 'Indonesian'),
       ('it', 'Italian'),
       ('ja', 'Japanese'),
       ('ko', 'Korean'),
       ('mr', 'Marathi'),
       ('pt', 'Portuguese'),
       ('ru', 'Russian'),
       ('sw', 'Swahili'),
       ('ta', 'Tamil'),
       ('te', 'Telugu'),
       ('tr', 'Turkish'),
       ('ur', 'Urdu'),
       ('vi', 'Vietnamese'),
       ('zh', 'Chinese');

CREATE TABLE formats
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO formats (name)
VALUES ('Hardcover'),
       ('Paperback'),
       ('Mass Market Paperback'),
       ('Leatherbound'),
       ('Graphic Novel'),
       ('Large Print'),
       ('Library Binding'),
       ('Board Book');

-- Books table
CREATE TABLE books
(
    id             SERIAL PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    description    TEXT,
    image_url      TEXT,
    isbn           VARCHAR(20),
    category_id    INT,
    format_id      INT,
    publisher      VARCHAR(100),
    published_date DATE,
    language_code  CHAR(2),
    pages          INT,
    date_updated   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    date_created   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id        INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    FOREIGN KEY (language_code) REFERENCES languages (code) ON DELETE SET NULL,
    FOREIGN KEY (format_id) REFERENCES formats (id) ON DELETE SET NULL,
    CONSTRAINT books_isbn_user_unique UNIQUE (isbn, user_id)
);

CREATE TABLE book_stocks
(
    id          SERIAL PRIMARY KEY,
    book_id     INT                                     NOT NULL,
    user_id     INT                                     NOT NULL,
    code        CHAR(10) UNIQUE                         NOT NULL,
    -- 0: available, 1: not available, 2: booked, 3: damaged
    status      SMALLINT CHECK (status IN (0, 1, 2, 3)) NOT NULL DEFAULT 0,
    location_id INT,

    -- when the book is status 2: booked, this field must be informed
    customer_id INT,

    -- Constraint: if status is 2, customer_id must be NOT NULL
    CHECK (
        (status = 2 AND customer_id IS NOT NULL) OR
        (status != 2 AND customer_id IS NULL)
        ),

    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    FOREIGN KEY (location_id) REFERENCES locations (id),
    FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE authors
(
    id      SERIAL PRIMARY KEY,
    name    VARCHAR(100) NOT NULL UNIQUE,
    user_id INT          NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE book_authors
(
    book_id   INT NOT NULL,
    author_id INT NOT NULL,
    user_id   INT NOT NULL,
    PRIMARY KEY (book_id, author_id),
    FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- triggers
CREATE
OR REPLACE FUNCTION enforce_customer_id_null()
RETURNS TRIGGER AS $$
BEGIN
  -- Si el nuevo status NO es 2, seteamos customer_id a NULL
  IF
NEW.status != 2 THEN
    NEW.customer_id := NULL;
END IF;

RETURN NEW;
END;
$$
LANGUAGE plpgsql;

CREATE TRIGGER trg_customer_id_null
    BEFORE UPDATE
    ON book_stocks
    FOR EACH ROW
    WHEN (OLD.status IS DISTINCT FROM NEW.status)
EXECUTE FUNCTION enforce_customer_id_null();
