INSERT INTO app_labels (language, code, text)
VALUES ('en', 'GROUPS', 'Groups'),
       ('en', 'GROUP', 'Group'),
       ('en', 'NO_GROUP', 'No group'),
       ('en', 'NO_MEMBERS', 'No members'),
       ('en', 'MANAGE_GROUPS', 'Manage groups'),
       ('en', 'ADD_GROUP', 'Add group'),
       ('en', 'EDIT_GROUP', 'Edit group'),
       ('en', 'DELETE_GROUP', 'Delete group'),
       ('en', 'DELETE_GROUP_DESC', 'Are you sure that you want to remove this group? Customers in this group will not be deleted.'),
       ('en', 'GROUP_MEMBERS', 'Group members'),
       ('en', 'ADD_MEMBERS_TO_GROUP', 'Add members'),
       ('en', 'TOTAL_CUSTOMERS', 'Customers'),
       ('en', 'SNACKBAR_NEW_GROUP_ADDED', 'Group added'),
       ('en', 'SNACKBAR_GROUP_UPDATED', 'Group updated'),
       ('en', 'SNACKBAR_DELETED_GROUP', 'Group deleted'),

       ('ca', 'GROUPS', 'Grups'),
       ('ca', 'GROUP', 'Grup'),
       ('ca', 'NO_GROUP', 'Sense grup'),
       ('ca', 'NO_MEMBERS', 'Sense membres'),
       ('ca', 'MANAGE_GROUPS', 'Gestionar grups'),
       ('ca', 'ADD_GROUP', 'Afegir grup'),
       ('ca', 'EDIT_GROUP', 'Editar grup'),
       ('ca', 'DELETE_GROUP', 'Eliminar grup'),
       ('ca', 'DELETE_GROUP_DESC', 'Segur que voleu eliminar aquest grup? Els clients d''aquest grup no s''eliminaran.'),
       ('ca', 'GROUP_MEMBERS', 'Membres del grup'),
       ('ca', 'ADD_MEMBERS_TO_GROUP', 'Afegir membres'),
       ('ca', 'TOTAL_CUSTOMERS', 'Clients'),
       ('ca', 'SNACKBAR_NEW_GROUP_ADDED', 'Grup afegit'),
       ('ca', 'SNACKBAR_GROUP_UPDATED', 'Grup actualitzat'),
       ('ca', 'SNACKBAR_DELETED_GROUP', 'Grup eliminat'),

       ('es', 'GROUPS', 'Grupos'),
       ('es', 'GROUP', 'Grupo'),
       ('es', 'NO_GROUP', 'Sin grupo'),
       ('es', 'NO_MEMBERS', 'Sin miembros'),
       ('es', 'MANAGE_GROUPS', 'Gestionar grupos'),
       ('es', 'ADD_GROUP', 'Agregar grupo'),
       ('es', 'EDIT_GROUP', 'Editar grupo'),
       ('es', 'DELETE_GROUP', 'Eliminar grupo'),
       ('es', 'DELETE_GROUP_DESC', '¿Está seguro de que desea eliminar este grupo? Los clientes de este grupo no se eliminarán.'),
       ('es', 'GROUP_MEMBERS', 'Miembros del grupo'),
       ('es', 'ADD_MEMBERS_TO_GROUP', 'Agregar miembros'),
       ('es', 'TOTAL_CUSTOMERS', 'Clientes'),
       ('es', 'SNACKBAR_NEW_GROUP_ADDED', 'Grupo agregado'),
       ('es', 'SNACKBAR_GROUP_UPDATED', 'Grupo actualizado'),
       ('es', 'SNACKBAR_DELETED_GROUP', 'Grupo eliminado'),

       ('it', 'GROUPS', 'Gruppi'),
       ('it', 'GROUP', 'Gruppo'),
       ('it', 'NO_GROUP', 'Nessun gruppo'),
       ('it', 'NO_MEMBERS', 'Nessun membro'),
       ('it', 'MANAGE_GROUPS', 'Gestisci gruppi'),
       ('it', 'ADD_GROUP', 'Aggiungi gruppo'),
       ('it', 'EDIT_GROUP', 'Modifica gruppo'),
       ('it', 'DELETE_GROUP', 'Elimina gruppo'),
       ('it', 'DELETE_GROUP_DESC', 'Sei sicuro di voler rimuovere questo gruppo? I clienti di questo gruppo non verranno eliminati.'),
       ('it', 'GROUP_MEMBERS', 'Membri del gruppo'),
       ('it', 'ADD_MEMBERS_TO_GROUP', 'Aggiungi membri'),
       ('it', 'TOTAL_CUSTOMERS', 'Clienti'),
       ('it', 'SNACKBAR_NEW_GROUP_ADDED', 'Gruppo aggiunto'),
       ('it', 'SNACKBAR_GROUP_UPDATED', 'Gruppo aggiornato'),
       ('it', 'SNACKBAR_DELETED_GROUP', 'Gruppo eliminato');
